### ISSUE TITLE
Problem with RxAtomic

### ISSUE THREAD

**Issue by Ricardo1980** [quickbirdstudios/XCoordinator#102]
Hello,

My carthage file has:
```
github "ReactiveX/RxSwift" "5.0.1"
github "quickbirdstudios/XCoordinator" "1.5.0"
```

I am using Xcode 10.2.1

But when running my app, I receive:
```
dyld: Library not loaded: @rpath/RxAtomic.framework/RxAtomic
  Referenced from: /Users/Ricardo/Library/Developer/CoreSimulator/Devices/C7E0B26C-A1F1-476D-B56F-C9991E3094B9/data/Containers/Bundle/Application/DCBC149F-67E6-405E-9ABA-33E2DF3A0B41/Verv.app/Frameworks/XCoordinator.framework/XCoordinator
  Reason: image not found
```

What should I do?
BTW, I am not using Xcoordinator rx extension, if that helps.

I see this:
https://github.com/quickbirdstudios/XCoordinator/pull/74
But I don't see that RxSwift 5 creates RxAtomic framework, so, I cannot mark it as optional.
Any advice?

EDIT: I just realised RxAtomic is not available in RxSwift 5 anymore.
https://github.com/ReactiveX/RxSwift/issues/1964
What do I have to do?

Thanks a lot.

**Comment by pauljohanneskraft** [comment]
XCoordinator is currently not supporting RxSwift 5 - Please use RxSwift 4.x for now or refer to the branch of https://github.com/quickbirdstudios/XCoordinator/pull/87 directly to get beta support for it - it has not been thoroughly tested though - we would however be grateful for feedback whether there are currently any problems.

**Comment by Ricardo1980** [comment]
No problem.
I forked the project and removed everything about rx, and works fine.
