### ISSUE TITLE
Memory issues in the example app

### ISSUE THREAD

**Issue by Ricardo1980** [quickbirdstudios/XCoordinator#104]
Hi,

Just let you know that I found several memory issues in the example app.
It seems HomeViewController/HomeViewModel are not released properly and many of them are created. It seems NewsCoordinator and UserListCoordinator has the same issue.

To reproduce it, run the app, press Login and then logout several times.
Use Instruments to see it (Allocations instrument, filter using "coordinator")

![Screenshot 2019-06-24 at 10 32 26](https://user-images.githubusercontent.com/738681/60008325-cb6b8880-966b-11e9-95e8-0287096ae7e3.png)

**Comment by pauljohanneskraft** [comment]
Thank you very much for mentioning this - This problem was unfortunately not only connected to the Example app and will therefore soon be published in a new version (even before the 2.0.0 release).
It should be fixed with https://github.com/quickbirdstudios/XCoordinator/pull/107.
