### ISSUE TITLE
CocoaPods could not find compatible versions for pod "RxSwift"

### ISSUE THREAD

**Issue by daoan1412** [quickbirdstudios/XCoordinator#105]
[!] CocoaPods could not find compatible versions for pod "RxSwift":
 ```
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "RxSwift":
  In Podfile:
    RxCocoa (~> 5.0.0) was resolved to 5.0.0, which depends on
      RxSwift (~> 5)

    RxSwift (~> 5.0.0)

    XCoordinator/RxSwift (~> 1.0) was resolved to 1.5.0, which depends on
      RxSwift (~> 4.0)
```

**Comment by Ricardo1980** [comment]
Try to use this commit
https://github.com/quickbirdstudios/XCoordinator/commit/323368d5f347191e6bba06fff1b3d91c10c6da6b

It seems current version requires rxswift 4, and you are already installing rxswift 5, so, not a good idea to have rxswift 4 and 5 in the same project.

pod 'XCoordinator', :git => 'https://github.com/quickbirdstudios/XCoordinator.git', :commit => '323368d5f347191e6bba06fff1b3d91c10c6da6b'
