### ISSUE TITLE
Hot to pop viewController back?

### ISSUE THREAD

**Issue by alessioarsuffi** [quickbirdstudios/XCoordinator#106]
Hello guys, 

i've set up everything and I'm able to present viewControllerA, then on a button tap I trigger next viewController (viewControllerB).
What it's not clear to me, is how to go back via pop from B -> A.
I can call directly coordinator passing .trigger(.a) but this will cause in a new push, and not a .pop animation, is there something i'm missing? 
Thanks

        override func prepareTransition(for route: AppRoute) -> NavigationTransition {
    let mainStoryboard: UIStoryboard = UIStoryboard(name: "Main", bundle: Bundle.main)
    
    switch route {
    case .start:
      let viewModel = StartViewModel(router: anyRouter)
      var startViewController = mainStoryboard.instantiateViewController(withIdentifier: "SOStartViewController") as! StartViewController
      startViewController.bindViewModel(to: viewModel)
      return .push(startViewController)
      
    case .login:
      let viewModel = LoginViewModel(router: anyRouter)
      var loginViewController = mainStoryboard.instantiateViewController(withIdentifier: "LoginViewController") as! LoginViewController
      loginViewController.bindViewModel(to: viewModel)
      return .push(loginViewController) 
    }

This is my current Coordinator

**Comment by pauljohanneskraft** [comment]
You can add a new route to `AppRoute`, e.g. `pop`, then you can return a `.pop` transition in the `prepareTransition(for:)` method for that route case to solve that specific problem. 

In general, route cases abstract from different transitions, which you can find by looking at the different static functions defined on the `Transition` struct (You can find the documentation [here](https://quickbirdstudios.github.io/XCoordinator/)).

**Comment by alessioarsuffi** [comment]
Many thanks :)
