### ISSUE TITLE
What would be the best/recommended way to test a coordinator?

### ISSUE THREAD

**Issue by msebgf** [quickbirdstudios/XCoordinator#108]
I would like for example to test the root view controller for a coordinator to be an instance of XYXViewController, I was trying to something like this: 

    it("Should init with WelcomeViewController", closure: {
        let window = UIWindow()
        let coordinator = WelcomeCoordinator().anyRouter
        coordinator.setRoot(for: window)   
        expect(coordinator.viewController is WelcomeViewController).to(equal(true))
      })
      
and also test that triggering certain cases will return an instance of a correct ABCViewController

**Comment by pauljohanneskraft** [comment]
To check the `rootViewController` or `viewController` property, you can use the above mentioned approach. When using RedirectionCoordinator/RedirectionRouter, the two properties will return different values - for BaseCoordinator subclasses accessing the properties should always be the same (and is the case for all provided subclasses). Keep that in mind, if you are using RedirectionCoordinators/RedirectionRouters in your app.

To test transitions, I would propose to call the `prepareTransition(for:)` method (in case you actually need trigger the transition use `contextTrigger`) which will return you the transition "behind a route case". From that transition, you can access the `presentables` property, which will give you all presentables, which will be added to the view hierarchy (this is only ensured for provided transition types, if you define your own, you should to stick to that convention as well). That being said, a test similar to the one above could look like the following (I have not used that testing framework before, so I hope this makes sense):

```swift
it("Trigger welcome case") {
    let window = UIWindow()
    let coordinator = WelcomeCoordinator()
    let transition = coordinator.prepareTransition(for: .welcome)
    expect(transition.presentables.first is WelcomeViewController).to(equal(true))
}
```

In general, keep in mind that testing for example the `rootViewController` can easily result in failing tests when the view hierarchy changes at some later development stage (e.g. your NavigationCoordinator might be changed into a TabBarCoordinator for a redesign of your app), which makes your app's structure somewhat inflexible. However, that obviously completely depends on your project.

**Comment by msebgf** [comment]
Thanks @pauljohanneskraft that makes a lot of sense, it's just a matter of getting used to do TDD in the whole app development process.
