### ISSUE TITLE
iOS 13 beta, modal presentation issue

### ISSUE THREAD

**Issue by Narek1994** [quickbirdstudios/XCoordinator#109]
Hi

Just wanted to know when new version for iOS 13 will be available, right now running on Xcode 11, while presenting it shows with new style, I know that its a new behavior, but it would be great if we could set presentation style

Thanks.

**Comment by pauljohanneskraft** [comment]
You should be able to have that behavior already, we are not touching the `presentationStyle` property at all in the framework. Did you encounter a different behavior?

**Comment by Narek1994** [comment]
I will double check it, maybe its a mistake from my side, thanks.
