### ISSUE TITLE
How to trigger certain route after condition?

### ISSUE THREAD

**Issue by artemkalinovsky** [quickbirdstudios/XCoordinator#110]
Hi guys,

I have bunch of coordinators in my project and I need to trigger .loginScene route modally after 401 response code from server, give user ability to login again and continue from scene on which 401 error appeared, how I can do this?

Thanks!

**Comment by artemkalinovsky** [comment]
For this moment I've used next logic:

1) NotificationCenter.default.post(name:"DidLostAuthorization", object: nil) in APIClient
2) My AppDelegate have  `private let router = AppCoordinator().anyRouter`, so this router could be used for navigation to login scene
3) In AppDelegate:
```NotificationCenter.default.addObserver(self,
                                               selector: #selector(authorizationLost),
                                               name: "DidLostAuthorization",
                                               object: nil)```
and selector is triggering login scene modally

**Comment by pauljohanneskraft** [comment]
Can you call `router.trigger` in your `authorizationLost` method?

**Comment by artemkalinovsky** [comment]
Hi Paul,

yes, I've actually did it in my current implementation:)

**Comment by pauljohanneskraft** [comment]
Ok, then I would assume that this issue is closed. If there are any questions or problems left, feel free to reopen, comment or open additional issues, if necessary.
