### ISSUE TITLE
Is there a way to print the navigation stack?

### ISSUE THREAD

**Issue by msebgf** [quickbirdstudios/XCoordinator#123]
It would be very handy

**Comment by pauljohanneskraft** [comment]
I will close this issue, since it is possible by accessing the `children` property of any `BaseCoordinator` subclass. In case this does not fully answer your question or is not a solution you were looking for, feel free to add additional comments, reopen this issue or open additional issues.

**Comment by andschdk** [comment]
@pauljohanneskraft, I'm trying to understand the `children` array. To me it seems like view controllers are only in the array from `performTransition` is invoked and until the transition completes and `removeChildrenIfNeeded` is called. Am I understanding anything wrong here?
