### ISSUE TITLE
jump login page question 

### ISSUE THREAD

**Issue by ChandleWEi** [quickbirdstudios/XCoordinator#130]
Hi

   If I have a login page, no matter which page expires, I will jump to the login page. I don't know how to implement it in this framework.

**Comment by pauljohanneskraft** [comment]
Hey, @ChandleWEi!

there are many different options on how to communicate between parts of your code (e.g. coordinators), that I already stated [here](https://github.com/quickbirdstudios/XCoordinator/issues/82). If you only have a small amount of coordinator, [this issue](https://github.com/quickbirdstudios/XCoordinator/issues/55) might also be interesting for you. If you have a concrete problem and none of these options would work for you, feel free to reopen this issue or add new comments.
