### ISSUE TITLE
How to use UITabBarControllerDelegate with TabBarCoordinator?

### ISSUE THREAD

**Issue by ducanh92hust** [quickbirdstudios/XCoordinator#132]
I want to UITabBarControllerDelegate in TabBarCoordinator, but error like bellow photo
<img width="726" alt="Screen Shot 2019-10-13 at 20 05 38" src="https://user-images.githubusercontent.com/48211927/66716221-7f4c7b80-edf5-11e9-9d35-8f3200e5ed59.png">
any idea please?
Thanks!

**Comment by pauljohanneskraft** [comment]
BaseCoordinator is not a NSObject-subclass, which is why this won't work.

What you can do is create a separate class, which serves as the UITabBarControllerDelegate, e.g.:

```swift
class HomeTabBarCoordinatorDelegate: NSObject, UITabBarControllerDelegate {
    let router: UnownedRouter<HomeRoute>
    /* ... */
}
```

or 

```swift
class HomeTabBarCoordinatorDelegate: NSObject, UITabBarControllerDelegate {
    unowned var coordinator: HomeTabBarCoordinator
    /* ... */
}
```

You can then hold an object of this class strongly in your HomeTabBarCoordinator.

**Comment by ducanh92hust** [comment]
I tried, but it not working :(
![image](https://user-images.githubusercontent.com/48211927/66716840-bb370f00-edfc-11e9-8271-996c32bfda54.png)
![image](https://user-images.githubusercontent.com/48211927/66716847-c853fe00-edfc-11e9-943c-4cb85236ce25.png)
Help me :(

**Comment by pauljohanneskraft** [comment]
You need to hold that delegate strongly, in your case you are only holding it weakly through the delegate, but not otherwise

**Comment by ducanh92hust** [comment]
thanks for the answer!
