### ISSUE TITLE
Code signing "XCoordinatorRx.framework" failed.

### ISSUE THREAD

**Issue by peacemoon** [quickbirdstudios/XCoordinator#133]
I'm trying to release a version of my app using the latest version of XCoordinator (v2.0.4) installed via Carthage but receive the following error
````
Code signing "XCoordinatorRx.framework" failed.
````

I have tried both auto & manual signing settings but the error persists. Do you have any suggestion?

**Comment by peacemoon** [comment]
seems to be a wrong xcode setting from my side. Sorry for the false alarm.

**Comment by peacemoon** [comment]
Ok, it seems that the issue is really from `XCoordinator` framework when integrated using Carthage

According to this https://github.com/Flight-School/AnyCodable/issues/20, CURRENT_PROJECT_VERSION needs to be hardcoded to 1 when the Carthage project is generated from SPM.

**Comment by pauljohanneskraft** [comment]
I added the CURRENT_PROJECT_VERSION with the value of 1, reset the 2.0.4 release to that new commit and uploaded new binaries for the 2.0.4 release - can you let me know whether that works now?

**Comment by peacemoon** [comment]
Yes, It solved my problem, I can distribute my app to the AppStore, thank you for the quick response. It is really an annoying bug.
