### ISSUE TITLE
Help me ,  Thanks so much! 丷丷

### ISSUE THREAD

**Issue by cxxcapf** [quickbirdstudios/XCoordinator#135]
[https://github.com/cxxcapf/xcoordinator-issues-demo](url)

Above is my demo URL

**I have Appcoordinator like this:**
class Appcoordinator: NavigationCoordinator<AppRoute>

` switch route {
        case .login:
            let coordinator = LoginCoordinator()
            let nav = coordinator.rootViewController
            let tmp = BaseViewController()
            tmp.addChild(nav)
            tmp.view.addSubview(nav.view)
            nav.didMove(toParent: tmp)
            return .push(tmp)
        case .initial:
            let tab = MTabBarCoordinator()
            return .push(tab)
        }`

**LoginCoordinator --Implementation:**
`enum LoginRoute: Route {
    case initial
    case next(viewmodel: LoginViewModel)
}

class LoginCoordinator: NavigationCoordinator<LoginRoute> {
    init() {
        let nav = BaseNavigationController()
        nav.navigationBar.backgroundColor = UIColor.white
        super.init(rootViewController: nav, initialRoute: .initial)
    }

    override func prepareTransition(for route: LoginRoute) -> NavigationTransition {
        switch route {
        case .next(let model):
            let vc = LoginNextViewController()
            vc.viewmodel = model
            return .push(vc)
        case .initial:
            let first = LoginViewController()
            let model = LoginViewModel(router: unownedRouter)
            first.viewmodel = model
            return .push(first)
        }
    }

    deinit {
        print(self)  //this method do not work ???
    }
}`

The problem now is：**LoginRoute. next**    this method can not work

**Comment by cxxcapf** [comment]
i want keep the current root view level in demo， I am already have RxSwift and RxCocoa in my application,

**Comment by pauljohanneskraft** [comment]
I ran your test and I do understand the problem - Please keep in mind how we changed the reference model in XCoordinator. To keep a reference to an existing coordinator, please make sure to specify it as a presentable in the transition it is introduced into the view hierarchy. In this case, I would suggest replacing `Appcoordinator.prepareTransition` with the following implementation:

```swift
override func prepareTransition(for route: AppRoute) -> NavigationTransition {
    switch route {
    case .login:
        let coordinator = LoginCoordinator()
        let tmp = BaseViewController()
        return .multiple(
            .embed(coordinator, in: tmp),
            .push(tmp)
        )
    case .initial:
        let tab = MTabBarCoordinator()
        return .push(tab)
    }
}
```

This way, it is ensured, that Appcoordinator is holding a strong reference to LoginCoordinator as long as it is part of the view hierarchy. Alternatively, you can also call `addChild` in your Appcoordinator to add the login coordinator as a child of the Appcoordinator and therefore holding a strong reference from the Appcoordinator to the LoginCoordinator.

As an explanation to what is going on in the background:
You are creating a LoginCoordinator and by executing the `LoginRoute.initial`, you are injecting an unowned reference of this LoginCoordinator to the `LoginViewModel`. After releasing the strong reference to the LoginCoordinator (when the execution of `Appcoordinator.prepareTransition` is finished), it is no longer in memory and therefore, you cannot access it (which is why accessing the LoginCoordinator later on is failing). By adding the LoginCoordinator as a child of Appcoordinator (either by using it in a transition or by calling addChild), XCoordinator will create a strong reference from the Appcoordinator to the LoginCoordinator as long a LoginCoordinator's rootViewController is in the view hierarchy. If you are unsure about ARC in Swift, please read [this document](https://docs.swift.org/swift-book/LanguageGuide/AutomaticReferenceCounting.html) first.

**Comment by cxxcapf** [comment]
Thanks, I can understand the principle of arc. At present, I understand the API of Xcoordinator too shallow.  

Especially for, multiple related APIs, it is a bit difficult to understand from readme and docs, but I really like Xcoordinator.

I just saw Xcoordinator a month ago, I used a new project to do the architecture with it, and now I am stuck with this problem.

The solution is really timely, let me try it.
Best regards!

**Comment by pauljohanneskraft** [comment]
We also provide [an example app](https://github.com/quickbirdstudios/XCoordinator-Example) and [two presentations](https://github.com/quickbirdstudios/XCoordinator-Talks) with each containing an example app and slides, which should be self-explanatory. You can also pose questions at [our Slack workspace](https://join.slack.com/t/xcoordinator/shared_invite/enQtNDg4NDAxNTk1ODQ1LTkxYzE3MDM5ZGY1MTVmY2NhNjI0Y2JiYmQ5NTdjZDczZDRjZTg1ZmJlOTZmODYyYzMyYWQ0NzhlNGNkMGIzYjQ), if you want.

**Comment by cxxcapf** [comment]
The problem now is that the memory is not released.
These two classes are not released
**LoginViewController**。 **LoginViewModel**  you can debug it

`class LoginViewModel {

    private let router: UnownedRouter<LoginRoute>!

    init(router: UnownedRouter<LoginRoute>) {
        self.router = router
    }

    func shownext() {
        self.router.trigger(.next(viewmodel: self))
    }

    deinit {
        print(self)
    }
}`


`class BaseViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    deinit {
        print(self)
    }
}
`

Already written::::deinit

**Comment by pauljohanneskraft** [comment]
They will not be released until they are no longer part of the view hierarchy. Remove them from the view hierarchy and they should be released from memory as well.

**Comment by cxxcapf** [comment]
> They will not be released until they are no longer part of the view hierarchy. Remove them from the view hierarchy and they should be released from memory as well.
What you mean is that although my interface returns from the loginviewcontroller to the tabbarcontroller, is the loginviewcontroller still in the current view hierarchy?

**Comment by pauljohanneskraft** [comment]
The app starts with a tab bar, then when you tap on the text, it pushes a viewController and when tapping the text on the new viewController, it pushes a new viewController again, right? That means, you can always tap on the `Back` button in the top left corner to go back to the last one (except if you hide that obviously). Please take a look at the other transitions as well, which might fit your use case better (e.g. present, dismiss, set, etc). They normally call a similarly named UIKit method internally when being performed.

**Comment by cxxcapf** [comment]
According to your code, run my demo, you will find that you enter the loginviewcontroller. When the gesture returns, the two classes are not released. However, what is even more strange is that if we enter the loginviewcontroller again, the console outputs all the related classes of the loginviewcontroller. Released

**Comment by cxxcapf** [comment]
> The app starts with a tab bar, then when you tap on the text, it pushes a viewController and when tapping the text on the new viewController, it pushes a new viewController again, right? That means, you can always tap on the `Back` button in the top left corner to go back to the last one (except if you hide that obviously). Please take a look at the other transitions as well, which might fit your use case better (e.g. present, dismiss, set, etc). They normally call a similarly named UIKit method internally when being performed.


tha app start with a navigation controller, the tab bar is first/root of the navigationcontroller viewcontrollers

**Comment by pauljohanneskraft** [comment]
ok, can you please check whether the `LoginViewController` is still in the view hierarchy using the View debugger. It needs to be removed so that XCoordinator actually removes its coordinator.

**Comment by cxxcapf** [comment]
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/10556278/67286013-34c0b280-f50b-11e9-8f17-15f825e316bf.png">
This is the first time I returned the tabbar interface from the loginviewcontroller.

**Comment by cxxcapf** [comment]
![E73841EC-A765-4309-A5DD-971D8CDDABCA](https://user-images.githubusercontent.com/10556278/67286738-7f8efa00-f50c-11e9-9b61-fa8afbeecf63.png)
This is the second time I enter the  loginviewcontroller.

**Comment by cxxcapf** [comment]
When I enter the loginviewcontroller again, the console outputs all the related classes of the loginviewcontroller. Released  

and  Loginviewcontroller replaced firstviewcontroller!

unbelievable!

**Comment by pauljohanneskraft** [comment]
Hey @cxxcapf, 

I have found a solution to your problem. A presentable is removed as a child, if its `viewController` property is either nil or not in a view hierarchy. This means that you can override the `viewController` property in your child coordinator to not specify its `rootViewController` which is the default implementation, but instead something like the following:

```swift
override var viewController: UIViewController! {
    rootViewController.viewControllers.first { $0 is LoginViewController }
}
```

Let me know, if this solves your problem!
