### ISSUE TITLE
Problem with presenting new coordinator

### ISSUE THREAD

**Issue by Ljuka** [quickbirdstudios/XCoordinator#138]
Hi to everyone :)

After I updated iPhone to version 13.1.3 the problem with presenting new coordinators occurred. I made the simplest project to test it where I have 2 coordinators (AppCoordinator and MainCoordinator) and 2 screens (Splash screen and Main screen). When Main screen appears it looks like it was presented, not pushed - the white space on the top of the screen is SplashVC from other coordinator and I can swipe the current screen up and down. Here's image bellow

![IMG_0218](https://user-images.githubusercontent.com/29049504/67774092-130c8180-fa5d-11e9-8e56-b17f68720e74.PNG)

First I have AppCoordinator from where I'm presenting (new) MainCoordinator.
Here's code from my AppCoordinator:
>
     override func prepareTransition(for route: AppRoute) -> NavigationTransition {
        switch route {
        case .splash:
            let splashVC = SplashVC.instantiateFromNib()
            let viewModel: SplashVM = SplashVM(provider: provider)
            splashVC.bind(to: viewModel)
            viewModel.router = unownedRouter
            return .push(splashVC)
        case .exit:
            let coordinator = MainCoordinator(provider)
            return .present(coordinator)
        }
    }

And the code from MainCoordinator:

>
    class MainCoordinator: NavigationCoordinator<MainRoute> {
        init(){
           super.init(initialRoute: .main)
         }

    override func prepareTransition(for route: MainRoute) -> NavigationTransition {
        switch route {
         case .main:
            let viewController = MainVC.instantiateFromNib()
            let viewModel: MainVM = MainVM(provider: provider)
            viewController.bind(to: viewModel)
            viewModel.router = unownedRouter
            return .push(viewController)
          }
       } 
    } 

So, the question is if there's any way to avoid present like screens when I want to add new coordinator and how to do that? 😄

**Comment by pauljohanneskraft** [comment]
Sure, this is due to a change in UIKit in the iOS 13 SDK - The default `modalPresentationStyle` has been changed from `.fullscreen` to `.automatic` leading to this behavior. You can add the line `coordinator.rootViewController.modalPresentationStyle = .fullscreen` to revert to the old presentation style.
