### ISSUE TITLE
How navigate to two coordinator with the same navigation ??

### ISSUE THREAD

**Issue by 5ldkamal** [quickbirdstudios/XCoordinator#141]

**Comment by pauljohanneskraft** [comment]
Could you please be more specific about your question?

**Comment by 5ldkamal** [comment]
class FirstCoordinator: NavigationCoordinator<FirstRoute> {
    /* ... */
    
    override func prepareTransition(for route: FirstRoute) -> NavigationTransition {
        switch route {
        case .secondCoordinator:
            let secondCoordinator = SecondCoordinator(rootViewController: self.rootViewController)
            addChild(secondCoordinator)
            return .none() 
            // you could also trigger a specific initial route at this point, 
            // such as `.trigger(SecondRoute.initial, on: secondCoordinator)`
        }
    }
}

How to implement addChild ??

**Comment by pauljohanneskraft** [comment]
You do not need to implement `addChild` yourself. It is already implemented in `BaseCoordinator` and therefore inherited by all its subclasses.

**Comment by pauljohanneskraft** [comment]
I think, this has already been answered in https://github.com/quickbirdstudios/XCoordinator/issues/139. I'm closing this for now - feel free to add more questions for reopening the issue, if it still persists.
