### ISSUE TITLE
deeplink question

### ISSUE THREAD

**Issue by lafalex** [quickbirdstudios/XCoordinator#142]
Hi, thanks for the repo, I'm starting to use it in my application and it's nice.
I have a question about deeplink (universal deeplink after tap a http link)

if the app is not launched, and the user is not yet connected, i would like to show the login page, wait the user log into the page, show the home and push the product page corresponding to the product ID in the url

I created a route like :
```
case .deep(let productID):
            return deepLink(AppRoute.login, AppRoute.home, AppRoute.showProduct(productID))
```

And in appdelegate:
```
router.trigger(AppRoute.deep(productID), with: TransitionOptions(animated: false)) {
            print("hello")
}
```

The chain is good but how to wait on login page, so the user can enter its login password before to go to home ? is it possible ?

**Comment by pauljohanneskraft** [comment]
Hey - great to hear that!

We encountered this problem already as well, but for notifications. Our solution was to store the information (in this case the product id) in one of the coordinators (as an optional stored property) and change the transition for a route depending on an existing value or not. Example:

```swift
class AppCoordinator: NavigationCoordinator<AppRoute> {
    var productId: Product.ID?

    override func prepareTransition(for route: AppRoute) -> NavigationTransition {
        switch route {
        case .product(let id):
            if isLoggedIn() {
                return prepareTransition(for: .deep(productId))
            } else {
                self.productId = productId 
                // wait until loginSuccessful is triggered for productId to be used
                return .none()
            }
        case .loginSuccessful:
            if let productId = productId {
                self.productId = nil
                // make sure to remove productId, so that next login does not open product again
                return prepareTransition(for: .deep(productId))
            } else {
                return prepareTransition(for: .home)
            }
        /* ... */
        }
    }
}
```

**Comment by lafalex** [comment]
ok it's clear for me and very usefull, thanks a lot!
