### ISSUE TITLE
Deep linking NO animation

### ISSUE THREAD

**Issue by msebgf** [quickbirdstudios/XCoordinator#143]
I'm wondering if there is a way to have deep linking without animation.

I've set all animations in the transitions to '.none', but when using deep linking I can still see a flickering set of view Controllers.

Scenario:

I have 10 views and i want to jump over to the 10th, but is important to keep the stack of views to be able to go back to previous steps.

Any help is appreciated.

**Comment by pauljohanneskraft** [comment]
Please take a look at https://github.com/quickbirdstudios/XCoordinator/issues/136. It should cover the same or a very similar problem. 

If the flickering is non-animated (i.e. the viewController is not really moving, but you can get a glimpse of it anyways), this might just be a UIKit problem. In these cases, please try to imitate that behavior using regular UIKit code. If the problem does not exist using regular UIKit code, feel free to open an issue describing what transitions are performed.

**Comment by msebgf** [comment]
Awesome dude! thanks a lot!
