### ISSUE TITLE
fatal error with deepLink & addChild

### ISSUE THREAD

**Issue by matinouf** [quickbirdstudios/XCoordinator#145]
I'm using deepLink for received push notification

**This is my deepLink:**
`deepLink(AppRoute.main, MainRoute.home ,HomeRoute.medicalRecords, MedicalRecordRoute.prescriptionPage)`

**(AppCoordinator: NavigationCoordinator)      _present ⤦_
(MainCoordinator: TabBarCoordinator)     _select ⤦_
 (HomeCoordinator: NavigationCoordinator)     _addChild ⤦_
(MedicalCoordinator: NavigationCoordinator)**

until `HomeRoute.medicalRecords` everything is OK. But when I try to navigate to `MedicalRecordRoute.prescriptionPage`, This fatal error being appear:

> Fatal error: Could not find appropriate router for prescriptionPage. The following routes could not be triggered: [MedicalRecord.MedicalRecordRoute.prescriptionPage]

how to solve this?

**Comment by pauljohanneskraft** [comment]
oh, this is a new case - can you try the replacing the transition for HomeRoute.medicalRecords to the following:

```swift
extension Transition {
    static func addChild(_ child: Presentable) -> Transition {
        Transition(presentables: [child], animationInUse: nil) { _, _, completion in
            completion?()
        }
    }
} 
```

It probably looks like this:

```swift
case .medicalRecords:
    let coordinator = MedicalRecordCoordinator()
    addChild(coordinator)
    return .none()
```

and you can now change it to this:

```swift
case .medicalRecords:
    let coordinator = MedicalRecordCoordinator()
    return .addChild(coordinator)
```

Hope that helps!

**Comment by pauljohanneskraft** [comment]
For some background information: 

Deep linking is currently implemented in a way, that it accesses the presentables entered into the view hierarchy via the `presentables` property of a transition. If you specify `Transition.none()` as a transition for one of these routes, it cannot find the right router to trigger the route on. By creating an empty transition, which specifies that presentable in its `presentable` property, it is automatically added as a child to the parent coordinator and it can also be found by the deep linking functionality.

**Comment by matinouf** [comment]
> For some background information:
> 
> Deep linking is currently implemented in a way, that it accesses the presentables entered into the view hierarchy via the `presentables` property of a transition. If you specify `Transition.none()` as a transition for one of these routes, it cannot find the right router to trigger the route on. By creating an empty transition, which specifies that presentable in its `presentable` property, it is automatically added as a child to the parent coordinator and it can also be found by the deep linking functionality.

**Thank You**
You'r right

**problem solved**
