### ISSUE TITLE
Not using RxSwift still adds RxSwift as a dependency

### ISSUE THREAD

**Issue by Rion-Kaneshiro** [quickbirdstudios/XCoordinator#162]
I did not look through all the code but is it really necessary to import RxSwift as a dependency if you only gonna use Combine?

**Comment by pauljohanneskraft** [comment]
Hey @Rion-Kaneshiro!

You are using Swift Package Manager, right? 
RxSwift is part of the dependencies of the whole package, but when you select to only use `XCoordinator.framework` and/or `XCoordinatorCombine.framework` you should neither be able to import RxSwift (unless you are importing it from elsewhere) nor should it be linked.

In case that assumption is wrong, please let me know. As far as I know, there is not yet an option to specify external dependencies for specific targets only, but at the moment it should only result in RxSwift to be downloaded but never used.

**Comment by Rion-Kaneshiro** [comment]
@pauljohanneskraft 

I only added the main framework and the combine part and RxSwift was added as a dependency and I can import it like any other Framework from SPM.

I guess the only way to really separate it is by having a separate project with a separate Package file to separate it cleanly.

**Comment by pauljohanneskraft** [comment]
I have just tried this and RxSwift is not actually added as a dependency. It is shown in the left bar in the section "Swift Package Dependencies", but trying to use "import RxSwift" in code does not work - i.e. it is not actually linked, but simply shown in the bar even though it is not used.
