### ISSUE TITLE
How to turn off the automatic swipe to go back in navigation controller? 

### ISSUE THREAD

**Issue by Krauler56** [quickbirdstudios/XCoordinator#165]
Is it possible in an easy way to disable this?

**Comment by pauljohanneskraft** [comment]
Hey @Krauler56!

Sure, to control this behavior, every UINavigationController has an `interactivePopGestureRecognizer` property. Having said that, you can easily disable that gesture recognizer like the following:

```swift
rootViewController.interactivePopGestureRecognizer?.isEnabled = false
```

**Comment by Krauler56** [comment]
I tried it, and it doesn't work because of interactivePopGestureRecognizer is nil
