### ISSUE TITLE
how can I do if I don't want animation during push with navagationController

### ISSUE THREAD

**Issue by panicfrog** [quickbirdstudios/XCoordinator#166]
how can I do if I don't want animation during push with navagationController

**Comment by sdgroot** [comment]
Trigger the route like this: `coordinator.trigger(.myRoute, with: TransitionOptions(animated: false))`.

**Comment by pauljohanneskraft** [comment]
This should fully answer your question - if there are additional questions, feel free to add more comments or open new issues.
