### ISSUE TITLE
Combine TabBarCoordinator with NavigationCoordinator

### ISSUE THREAD

**Issue by loplopLover** [quickbirdstudios/XCoordinator#175]
Hello,
I have a TabBarCoordinator, and I want to implement a router which is triggered from navigation bar. How can I solve this? Should I create a parent route which includes both of coordinators for TabBar and Navigation or is there a simpler solution for this? I don't want trigger this router (in navigation bar) for each coordinator in TabBarCoordinator. Is it possible to implement a centralized router for navigation bar?
Thanks

**Comment by pauljohanneskraft** [comment]
I'm not quite sure, whether I understand your issue. 

So, you have a UITabBarController with multiple UINavigationControllers as its children? From each or multiple of these UINavigationControllers you want to perform the same transition, right?

Would it be an option to handle the transition in the TabBarCoordinator and injecting it as an UnownedRouter into the child coordinators?

**Comment by pauljohanneskraft** [comment]
Closed due to inactivity.
