### ISSUE TITLE
Using a custom UINavigationController subclass?

### ISSUE THREAD

**Issue by jesster2k10** [quickbirdstudios/XCoordinator#178]
Hey,

is it possible to use this library with a custom UINavigationContorller subclass? I can’t seem to find anything in the readme that suggests this. 

Also, how are you supposed to handle customising the navigation bar when using the Coordinator pattern? I find it a bit confusing since you no longer have access to the UITabBarController or UINavigationController but rather just a wrapper around it.

Any help will be appreciated

**Comment by pauljohanneskraft** [comment]
Hey - you can definitely use a custom UINavigationController subclass - simply inject your own navigation controller in the initializer of your NavigationCoordinator. If you require your RootViewController to have the type of your custom subclass, you can also write a wrapper around BaseCoordinator that is quite similar to what NavigationCoordinator does.

You can still access the rootViewController of a given coordinator using its rootViewController property - Moreover, you can also access a navigationController/tabBarController using the respective properties of UIViewController.

**Comment by jesster2k10** [comment]
Okay thank you for the clarification. I've ran into another issue but I'll open up a new one for that.
