### ISSUE TITLE
iOS 13+ Initialization of a UIWindow with SceneDelegate

### ISSUE THREAD

**Issue by justinsherwood** [quickbirdstudios/XCoordinator#182]
As of iOS 13, the UIWindow of an application can be initialized in the SceneDelegate class to allow for multi-window support. [hackingwithswift.com - What’s new in iOS 13?](https://www.hackingwithswift.com/articles/193/whats-new-in-ios-13) 

I was having issues initializing the rootViewController of my AppCoordinator using the methods stated in the README and example project. Setting a coordinator's root UIWindow in the AppDelegate class resulted in a black screen after initialization of my application for iOS 13+.

I used the following solution to resolve this issue.

Would this be the recommended approach for setting the root UIWindow of a coordinator for iOS 13+?

## AppDelegate.swift
```swift
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    var window: UIWindow?
    let router = AppCoordinator().strongRouter

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        if #available(iOS 13, *) { } else {
            self.window = UIWindow(frame: UIScreen.main.bounds)
            if let window = self.window {
                router.setRoot(for: window)
            }
        }
        return true
    }
}
```
<br>

## SceneDelegate.swift
```swift
@available(iOS 13.0, *)
class SceneDelegate: UIResponder, UIWindowSceneDelegate {
    var window: UIWindow?
    let router = AppCoordinator().strongRouter

    func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
        if let windowScene = scene as? UIWindowScene {
            self.window = UIWindow(windowScene: windowScene)
            if let window = self.window {
                router.setRoot(for: window)
            }
        }
    }
}
```

**Comment by pauljohanneskraft** [comment]
Yes, this is the recommended approach - thanks for the information about the README. I will try to adapt it shortly 😊
