### ISSUE TITLE
Impossible to control interactivePopGestureRecognizer?

### ISSUE THREAD

**Issue by leocallas** [quickbirdstudios/XCoordinator#183]
How is it possible to control interactivePopGestureRecognizer? 
I get this error when I'm setting the UIGestureRecognizerDelegate to detect swipe back gesture:

Fatal error: Please don't set a custom delegate on UINavigationController.interactivePopGestureRecognizer.

**Comment by pauljohanneskraft** [comment]
Is there a specific reason, why you want to control the interactivePopGestureRecognizer?

**Comment by leocallas** [comment]
I want to detect swipe to back gesture and show alert for example, before it goes back and then I'll decide by the action of the alert to pop navigation or not.

**Comment by pauljohanneskraft** [comment]
Just curious: Could you implement this by writing a custom `UINavigationControllerDelegate`? If yes, feel free to create your own custom subclass of `NavigationAnimationDelegate`.
