### ISSUE TITLE
Viewcontroller Can not release when use gesture to dismiss

### ISSUE THREAD

**Issue by eyuxin** [quickbirdstudios/XCoordinator#187]
I use .present(LoginCoordinator()) in prepareTransition.
I'm going to call the trigger method to call .dismiss when I click the close button, that's fine, of course.
But when I use the slide to make my 'presentViewController' disappear, this 'presentViewController' has a memory leak.
I know because the coordinator didn't call 'removeChildrenIfNeeded', but, what should I do?

**Comment by eyuxin** [comment]
I solved this issue in the following way:
`override func presented(from presentable: Presentable?) {
        super.presented(from: presentable)
        hookPullToDismiss()
    }
    
    private func hookPullToDismiss() {
        let block: AspectBlock = { [weak self] (object) in
            if let nav = object.instance as? UINavigationController, nav.isBeingDismissed {
                self?.unownedRouter.childTransitionCompleted()
            }
        }
        rootViewController.hook(#selector(UIViewController.viewDidDisappear(_:)), position: .after, usingBlock: block)
    }`

**Comment by iDevid** [comment]
Have you checked if there is a memory leak inside your controller first?

**Comment by eyuxin** [comment]
> Have you checked if there is a memory leak inside your controller first?

Sorry for the late reply. I checked that is not a memory leak inside my controller.
This issue only happens when I use gesture to dismiss my controller.

**Comment by pauljohanneskraft** [comment]
There is not really a memory leak, but rather it is not releasing the viewController until there is any other transition being performed. We could not yet find a way to get notified about a viewController being dismissed which does not involve method swizzling - in case you are aware of a method, we would be glad to hear about it.

**Comment by eyuxin** [comment]
Yep, I have changed this issue's title.
I'm also using method swizzling to solve this problem by hooking the coordinator.rootViewController' viewDidDisappear method and judging UINavigationController.isBeingDismissed and then calling the unownedRouter.childTransitionCompleted()
It seems to be working well so far, would you guys consider adding it to the project?

**Comment by kevinrenskers** [comment]
I'm running into the same problem where a coordinator that is shown modally is not released when you drag to close it. Is there a known workaround yet?

**Comment by pauljohanneskraft** [comment]
There is a workaround, but is not really nice... It would in one way or another involve method swizzling of viewDidAppear of any viewController to be presented. In case you are using RxSwift in your project already, [this extension](https://github.com/quickbirdstudios/XCoordinator-Example/blob/master/XCoordinator-Example/Extensions/Presentable%2BRx.swift) in the example project can help you building something like this:

```swift
class SomeCoordinator: <some coordinator class> {

    let disposeBag = DisposeBag()

    override func prepareTransition(for route: RouteType) -> TransitionType {
        switch route {
        case .someRoute:
            let presentable = // could be a router, coordinator or viewController
            presentable.rx.dismissal
                .subscribe(onNext: { [weak self] _ in
                    self?.removeChildrenIfNeeded()
                })
                .disposed(by: disposeBag)
            return .someTransition(presentable)
        }
    }
}
```

This should actually be a functional workaround although it is not really nice to work with, I'm afraid, especially when handling these cases many times over.
