### ISSUE TITLE
DeepLink animation 

### ISSUE THREAD

**Issue by JK0369** [quickbirdstudios/XCoordinator#194]
When using a deep link, I want an animation in which each screen is pushed in turn, but only the last screen shows the animation. 

How can all the screens be animated one after the other?

`    override func prepareTransition(for route: SplashRoute) -> NavigationTransition {

        rootViewController.setNavigationBarHidden(true, animated: false)

        switch route {
        case .home:
            let homeCoordinator = HomeCoordinator(
                rootViewController: rootViewController,
                postTaskManager: postTaskManager,
                initialRoute: .home
            )
            return .addChild(homeCoordinator)

        case .deep:
            let router = HomeCoordinator(rootViewController: rootViewController, initialRoute: .home).strongRouter

            let vc = HomeBuilder.build(router: router)

            return deepLink(
                .home,
                HomeRoute.menu(vc),
                SideMenuRoute.profileMain,
                SideMenuRoute.homeCompanyMain
            )

        }
    }`

**Comment by pauljohanneskraft** [comment]
Hey @JK0369, this should actually be the intended behavior, so I would like to ask: How are you currently triggering the deeplink and what is actually happening at the moment?

**Comment by JK0369** [comment]
If the app notifies me, i will use it by triggering (.deep) on the AppDelegate. At this point, I want the push animation of the navigation controller to be applied to each screen.

When registering diplinks on 5 screens, push animation of navigation controller does not appear for each screen in turn. 

Push animation appears to work only for the last screen, the fifth screen. I want all 5 screens to appear in push animation one by one.

**Comment by JK0369** [comment]
i solved it. thank you for response
