### ISSUE TITLE
RxSwift 6 compatibility

### ISSUE THREAD

**Issue by pzmudzinski** [quickbirdstudios/XCoordinator#197]
It seems `XCoordinator/RxSwift` extension is broken with latest release of RxSwift:
```  
 XCoordinator/RxSwift (~> 2.0) was resolved to 2.0.7, which depends on
      RxSwift (~> 5.0)
```

Also code of extension doesn't seem to be compile with latest version of RxSwift (I've just tried to copy-paste it to my project):
```
extension Router {

    /// Use this to access the reactive extensions of `Router` objects.
    public var rx: Reactive<Self> {
        // swiftlint:disable:previous identifier_name
        Reactive(self)
    }
}
```

Error message: `'Reactive' requires that 'Self' be a class type`

I am setting new project with `RxSwift` and wanted to try `XCoordinator` as API seem to be well designed but it kind of blocks me. Any idea how to fix it?

**Comment by pauljohanneskraft** [comment]
Hey @pzmudzinski, RxSwift 6 compatibility will come with one of the next releases of XCoordinator. Thanks for the notification!
Now to the specific problem here at hand: What you could try is the following:

```swift
extension Router where Self: AnyObject {

    /// Use this to access the reactive extensions of `Router` objects.
    public var rx: Reactive<Self> {
        // swiftlint:disable:previous identifier_name
        Reactive(self)
    }
}
```

With this change, you ensure that the new requirement is met - However, I cannot say that everything will work the same as before, since I'm not familiar with all the source-breaking changes of RxSwift 6 and it might break the rx-extension for all the pure Router types, i.e. StrongRouter, WeakRouter and UnownedRouter, since they are structs not classes...

**Comment by pzmudzinski** [comment]
Yeah, it breaks with router subtypes. I have no idea how to add `rx` property to them.
As a total workaround I used this code:
```swift
extension Router {

    public func rxTrigger(_ route: RouteType, with options: TransitionOptions) -> Observable<Void> {
        Observable.create { [self] observer -> Disposable in
            self.trigger(route, with: options) {
                observer.onNext(())
                observer.onCompleted()
            }
            return Disposables.create()
        }
    }

    public func rxTrigger(_ route: RouteType) -> Observable<Void> {
        rxTrigger(route, with: TransitionOptions(animated: true))
    }
}
```

**Comment by pauljohanneskraft** [comment]
An alternative solution that would keep the same API is recreating the existing `Reactive` type in XCoordinator without the constraint to AnyObject.

The code would be the following:

```swift
public struct Reactive<Base> {
    public private(set) var base: Base

    public init(_ base: Base) {
        self.base = base
    }
}

extension Router {
    public var rx: Reactive<Self> {
        Reactive(self)
    }
}
```

The extensions to Reactive would stay exactly the same and users would not need to change any code themselves.

Of course, we would break the existing consistency of reusing the `Reactive` type of RxSwift, but a user could still use module prefixes to access the different types `RxSwift.Reactive` or `XCoordinatorRx.Reactive`.

**Comment by xxbic** [comment]
Any news about RxSwift 6 compatibility?

**Comment by pauljohanneskraft** [comment]
Hey @xxbic - I'm working on it!

You can find the current development here: https://github.com/quickbirdstudios/XCoordinator/pull/203

**Comment by ab-zephyr** [comment]
@pauljohanneskraft rxswift6 branch still has dependency on RxSwift 5 in podspec

**Comment by pauljohanneskraft** [comment]
@ab-zephyr Thanks for mentioning - I just adapted it.

**Comment by vvit** [comment]
@pauljohanneskraft thanks for your work, any plans to merge `rxswift6` branch into `master`?

**Comment by pauljohanneskraft** [comment]
Yes, there is news! There will be a 2.1.0 release in the very near future!
