### ISSUE TITLE
PageCoordinator issue.

### ISSUE THREAD

**Issue by Daniebro5** [quickbirdstudios/XCoordinator#198]
I'm using the PageCoordinator to display a Carousel inside a container in a view, but when the users go forward and back several times, the app crashes, it's a documented crash in [stackoverflow](https://stackoverflow.com/questions/24000712/pageviewcontroller-setviewcontrollers-crashes-with-invalid-parameter-not-satisf), but this fix doesn't work with XCoordinator, any help to solve my problem?

**Comment by pauljohanneskraft** [comment]
I'm not sure whether I understand the issue. 

Can you please provide more context on how you are using XCoordinator in the given context, what you have tried so far and whether it is most related to the TabBarAnimationDelegate, the TabBarCoordinator or specific transitions (e.g. TabBarTransition.set)?

**Comment by pauljohanneskraft** [comment]
You can plug in your custom `UIPageViewControllerDataSource` into PageCoordinator (see `init(rootViewController:dataSource:set:direction:)`) that fixes this issue. I, unfortunately, cannot help with a specific implementation, but you would need to write that datasource without XCoordinator as well...
