### ISSUE TITLE
Put a page inside its own viewController

### ISSUE THREAD

**Issue by fabian1122** [quickbirdstudios/XCoordinator#211]
Hi everyone

I have a problem with the page, I want to put inside a custom view, but, I can't find a way to do it, someone who has done something similar, please with your help. I leave an image with what I want to do

Thanks

Thanks
![Simulator Screen Shot - iPhone 8 - 2021-10-03 at 17 52 30](https://user-images.githubusercontent.com/7807220/135774232-fc2f116e-6366-4e9a-ac26-b99bdb588587.png)

**Comment by pauljohanneskraft** [comment]
I'm not sure how this is actually related to XCoordinator. Closing this - if you happen to have a XCoordinator-related question, feel free to open new issues or reopen this one.
