### ISSUE TITLE
Access the current used router

### ISSUE THREAD

**Issue by ghadeermohameedelmahdy** [quickbirdstudios/XCoordinator#215]
how to get current router from any file, to enable present the root tabviewcontroller for example?

**Comment by pauljohanneskraft** [comment]
There is no such functionality as of now in XCoordinator. You can, however, use Service Locator / Dependency Injection techniques to solve this issue. There is also no such thing as the "currently used router", as any router in existence might trigger a transition at any time (as is the case with UIKit's UIViewController).
