### ISSUE TITLE
Question: the animation only for the last screen in the deepLink flow

### ISSUE THREAD

**Issue by SzymonWojcik** [quickbirdstudios/XCoordinator#218]
First of all, thanks to all contributors for this wonderful package :) 

I have one question regarding the `deepLink` animation. By default triggering `deepLink` transition performs "one by one" animation in the deep link flow.

My question: is there an option to disable that behavior and show **only the last animation or maybe somehow show just needed animations** in that flow? I know it may be kind of achieved with `set(presentables:)` but it requires additional handling so I'd to avoid it.

Thanks in advance :)

**Comment by pauljohanneskraft** [comment]
Hey :) Unfortunately, this is not easily possible. However, there is a way to force certain TransitionOptions for a certain Transition by using the extension that is discussed in #136. 

So, in your case, you might want to force animated to true for the last transition and force it to false for the rest, maybe?

I'm sorry to not be of help with the limited information you provide. If you would like me to have a deeper look at this, please provide more information about what you are struggling with exactly.
