### ISSUE TITLE
RxSwift 6+ Compatibility Not Released to Cocoapods

### ISSUE THREAD

**Issue by jaron-m-lowe** [quickbirdstudios/XCoordinator#221]
@pauljohanneskraft  I see there was a PR for RxSwift 6+ compatibility. Are there any plans to release this version to Cocoapods?

https://github.com/quickbirdstudios/XCoordinator/pull/203

**Comment by illyaGordiyenkoDev** [comment]
Bump on this thread too, it'll be great to get this released

**Comment by pauljohanneskraft** [comment]
Sorry, I missed this one - it is not released as version 2.1.0.

**Comment by jaron-m-lowe** [comment]
> Sorry, I missed this one - it is not released as version 2.1.0.

Thanks so much for this @pauljohanneskraft!
