### ISSUE TITLE
SPM installation without Rx?

### ISSUE THREAD

**Issue by GeoSD** [quickbirdstudios/XCoordinator#229]
Hi! Is there any possibility to install XCoordinator by using SPM without RxSwift and ReactiveSwift?
Thanks in advance.

**Comment by pauljohanneskraft** [comment]
Hey @GeoSD 

Yes, it is possible to install XCoordinator without using RxSwift in your binary. It will still show up in the sidebar of Xcode though (maybe Apple has already fixed this, but last time I checked, they did not).

Simply add your package dependency like normal and for app targets only select `XCoordinator.framework` to be linked to your project. If you also select `XCoordinatorRx.framework`, then RxSwift will be added as a dependency.

If you are working on a library yourself, then use `.product(name: "XCoordinator", package: "XCoordinator")` as dependency for your target.

I hope this helps. To check, if it works, try adding `import RxSwift` to your project and if it does not build, then RxSwift is also not part of your app.

**Comment by Mordil** [comment]
@pauljohanneskraft Is it possible for y'all to split the RxSwift interop into a separate package for those who also use RxSwift (but not the same version)? SwiftPM fails to resolve, even if we don't use XCoordinator with RxSwift support
