### ISSUE TITLE
Support .push of NavigationCoordinator

### ISSUE THREAD

**Issue by lm2s** [quickbirdstudios/XCoordinator#48]
Hello.

Currently a `NavigationCoordinator` can't push another `NavigationCoordinator.` If we try to do so, it results in an UIKit exception `*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Pushing a navigation controller is not supported'`.

I believe a `Coordinator` should allow being shown in multiple ways and that there's a use case for this functionality. 

To make it work I think the base `NavigationCoordinator` (pusher) would just need to keep a reference to the `topViewController` of its `UINavigationController` before pushing the new `NavigationCoordinator` and the pushed `NavigationCoordinator` would have to use the pusher `UINavigationController` instead of creating one.
To rewind when a pop is made, the base `NavigationCoordinator` would just need to `popToViewController(topViewController)` and resume.

What are your thoughts on this?

**Comment by pauljohanneskraft** [comment]
Hey,

I like this idea, although then we could run into multiple issues such as the following:
- you cannot use the `set` transition with any of the two NavigationCoordinators
- what would be the behavior of `popToRoot` in the upper NavigationCoordinator?
- what if a user has a custom implementation on top of BaseCoordinator or the Coordinator-protocol - we cannot support this...
- It would introduce a dependency between Transition and NavigationCoordinator (as we would need to check whether there is a NavigationCoordinator and then set the rootViewController accordingly, etc).

I think this would introduce unnecessary complexity and the need for reading a lot of documentation or unintuitive APIs. The current proposed alternative would be a RedirectionCoordinator with a TransitionType of NavigationTransition. With this you simply have the same behavior as the lower coordinator, as it is executing all transitions with the rootViewController of the superCoordinator. I know, that this poses some of the above-mentioned problems (i.e. the behavior of `popToRoot` and `set`) as well, but it might help you with your current problem nonetheless.

**Comment by lm2s** [comment]
Thanks for the feedback, yes it might just be enough for my use case.

I was trying to adapt the example app (with the code in the main page) to use RedirectionCoordinator when showing the User but I'm getting an error when calling `super` (the compiler seems to be complaining that the `superCoordinator` in `superTransitionPerformer: superCoordinator` is not of the correct type):

`Must call a designated initializer of the superclass 'RedirectionCoordinator<UserRoute, NavigationTransition>' (aka 'RedirectionCoordinator<UserRoute, Transition<UINavigationController>>')`

```
init<T: TransitionPerformer>(superCoordinator: T, username: String) where T.TransitionType == NavigationTransition {
        let viewController = UserViewController.instantiateFromNib()
        super.init(viewController: viewController, superTransitionPerformer: superCoordinator, prepareTransition: nil)

        let viewModel = UserViewModelImpl(router: anyRouter, username: username)
        viewController.bind(to: viewModel)
}
```

Any idea as to why this is happening?

**Comment by pauljohanneskraft** [comment]
Ah, yes - thanks for mentioning, will be fixed in the next release 

For now, please put `AnyTransitionPerformer.init` around the superCoordinator.

i.e.:
```swift
init<T: TransitionPerformer>(superCoordinator: T, username: String) where T.TransitionType == NavigationTransition {
        let viewController = UserViewController.instantiateFromNib()
        super.init(viewController: viewController, superTransitionPerformer: AnyTransitionPerformer(superCoordinator), prepareTransition: nil)

        let viewModel = UserViewModelImpl(router: anyRouter, username: username)
        viewController.bind(to: viewModel)
}
```
