### ISSUE TITLE
Installation problem (Cocoapods)

### ISSUE THREAD

**Issue by adamsmaka** [quickbirdstudios/XCoordinator#54]
When I call pod install in terminal I receive a red error:
```
pod install
Analyzing dependencies
[!] Unable to find a specification for `XCoordinator (~> 1.0)`
```
Previously I was using :branch => 'feat/v1' so maybe this makes the problem?

**Comment by adamsmaka** [comment]
I know, I'm using `pod 'XCoordinator', '~> 1.0'` which doesn't work.

`[!] Unable to find a specification for `XCoordinator (~> 1.0)``

**Comment by pauljohanneskraft** [comment]
Did you try `pod update` as well?

**Comment by adamsmaka** [comment]
`pod update` fixed the problem! thank you so much! :) 

btw. also thanks for awesome framework. I love it.

**Comment by pauljohanneskraft** [comment]
Great to hear that! 🎉
