### ISSUE TITLE
The best way to get callback value for controller

### ISSUE THREAD

**Issue by devSC** [quickbirdstudios/XCoordinator#55]
A controller push to B controller, Then  B controller pop stack, is there have the best way for A controller to get callback value from B controller?

**Comment by pauljohanneskraft** [comment]
Hey,

there are probably a lot more ways to solve this problem, but I can think of the following two:

If you already have RxSwift and RxCocoa in your application, you can copy the `Presentable+Rx.swift` file from the Example application to get an observable when a viewController is dismissed / popped. Then you can connect the two viewControllers via the route:

```swift
enum ConnectedRoute: Route {
    case observeDismissal(PublishSubject<Void>)
    /* ... */
}

class ConnectedCoordinator: NavigationCoordinator<ConnectedRoute> {
    let disposeBag = DisposeBag()

    func prepareTransition(for route: ConnectedRoute) -> NavigationTransition {
        switch route {
            case .observeDismissal(publish):
                let viewController = UIViewController()
                viewController.rx.dismissal
                    .bind(to: publish)
                    .disposed(by: disposeBag)
            return .push(viewController)
            /* ... */
        }
    }
}
```

If you don't use RxSwift and Cocoa, you can do a similar approach by injecting a closure into the second viewController:

```swift 
class SecondViewController: UIViewController {
    var dismissal: (() -> Void)?
    
    func viewDidDisappear() {
        super.viewDidDisappear()
        
        if isBeingDismissed || isMovingFromParent {
            dismissal?()
        }
    }

enum ConnectedRoute: Route {
    case second(@escaping () -> Void) // not sure, if you need @escaping here
    /* ... */
}

class ConnectedCoordinator: NavigationCoordinator {
    /* ... */
   func prepareTransition(for route: ConnectedRoute) -> NavigationRoute {
        switch route {
            case .second(let dismissalClosure):
                let viewController = SecondViewController()
                viewController.dismissal = dismissalClosure
                return .push(viewController)
            /* ... */
        }
    }
```

I hope this helps! I would personally prefer the first solution, if you are already using RxCocoa in your application, otherwise solution 2 is very similar, except that you have to adapt the SecondViewController.

**Comment by devSC** [comment]
Got it, Thanks.

**Comment by lts1610** [comment]
@pauljohanneskraft : 
Can you provide an example of using `publish`?

**Comment by pauljohanneskraft** [comment]
@lts1610 : I'm not sure, what you mean by that - the first code block in my previous message uses a `PublishSubject`, so that could serve as an example. For further information about how a `PublishSubject` works, please consult the `RxSwift documentation`.

**Comment by lts1610** [comment]
@pauljohanneskraft : I understand how a `PublishSubject` works. However, look at the first code block of the example above, I see that you have just provided the way that the source view controller bind value to the publish subject only. So, I would like to see how to the destination view controller subscribes value of that `publish` subject.
p/s: Sorry for my English.

**Comment by pauljohanneskraft** [comment]
@lts1610 No worries, the following might help you for example:

```swift
let dismissSubject = PublishSubject<Void>()
return router.rx.trigger(. observeDismissal(dismissSubject))
    .flatMap { dismissSubject }
```

But depending on your use case, you might also just subscribe normally, if you need separate observables:

```swift
let dismissSubject = PublishSubject<Void>()

dismissSubject
   .subscribe(onNext: { /* ... */ })
   .disposed(by: disposeBag)

return router.rx.trigger(. observeDismissal(dismissSubject))
```

These code pieces could be found in Actions, but also may be used in all sorts of other places. I hope these code pieces help you. If you have a specific problem at hand, please explain it in more detail, since it may be easier to understand what you want to achieve.

**Comment by lts1610** [comment]
@pauljohanneskraft Yeap
For example, I have the `UserListCoordinator`.
```
enum UserListRoute: Route {
    case users
    case user(String)
}
class UserListCoordinator: NavigationCoordinator<UserListRoute> {
    override func prepareTransition(for route: UserListRoute) -> NavigationTransition {
        switch route {
        case .users:
            let viewController = UsersViewController.instantiateFromNib()
            let viewModel = UsersViewModelImpl(router: anyRouter)
            viewController.bind(to: viewModel)
            return .push(viewController, animation: .fade)
        case .user(let username):
            let coordinator = UserCoordinator(user: username)
            return .present(coordinator, animation: .default)
        }
    }
}
```
and the `UserCoordinator`
```
enum UserRoute: Route {
    case users
}
class UserCoordinator: NavigationCoordinator<UserRoute> {

    // MARK: - Init

    init(user: String) {
        super.init(initialRoute: .user(user))
    }

    // MARK: - Overrides

    override func prepareTransition(for route: UserRoute) -> NavigationTransition {
        switch route {
        case .users:
            return .dismiss()
        }
    }
}
```
 I want to refresh the list users of `UsersViewController` after the `UserViewController` is be dismissed by using `dismissSubject` as you mentioned above.

**Comment by pauljohanneskraft** [comment]
In this example you might simply want to include the PublishSubject into `UserListRoute.user` and then use `coordinator.rootViewController.rx.dismissal` to get an observable of the UserCoordinator being dismissed.

**Comment by lts1610** [comment]
Okay, let me try.
Thank you so much!

**Comment by lts1610** [comment]
@pauljohanneskraft 
I still stuck after trying to include the PublishSubject into `UserListRoute.user`. Could you give me a boilerplate code?

**Comment by pauljohanneskraft** [comment]
UserListRoute:
```swift
enum UserListRoute: Route {
    case user(String, PublishSubject<Void>)
    /* ... */
}

class UserListCoordinator: NavigationCoordinator<UserListRoute> {
    override func prepareTransition(for route: UserListRoute) -> NavigationTransition {
        switch route {
        case .users:
            let viewController = UsersViewController.instantiateFromNib()
            let viewModel = UsersViewModelImpl(router: anyRouter)
            viewController.bind(to: viewModel)
            return .push(viewController, animation: .fade)
        case .user(let username, let subject):
            let coordinator = UserCoordinator(user: username)
            coordinator.rootViewController.rx.dismissal
                .bind(to: subject)
                .disposed(by: disposeBag)
            return .present(coordinator, animation: .default)
        }
    }
}
```

**Comment by lts1610** [comment]
How to inject `subject` into `showUserAction` of `UsersViewModelImpl`?

``` swift
class UsersViewModelImpl: UsersViewModel, UsersViewModelInput, UsersViewModelOutput {

    // MARK: - Inputs

    lazy var showUserTrigger: InputSubject<String> = showUserAction.inputs

    // MARK: - Actions

    private lazy var showUserAction = Action<String, Void> { [unowned self] username in
        self.router.rx.trigger(.user(username))
    }
}
```

**Comment by pauljohanneskraft** [comment]
One implementation option for enabling the reloading would be to create a new Action, as in the following: 

```swift
class UsersViewModelImpl: /* ... */ {
    /* ... */
    private lazy var showUserAction = Action<String, Void> { [unowned self] username in
        let subject = PublishSubject<Void>()
        subject
            .subscribe(onNext: self.reloadingAction.inputs.onNext)
            .disposed(by: disposeBag)
        return self.router.rx.trigger(.user(username, subject))
    }

   private lazy var reloadAction = Action<Void, [String]> { 
       return .just([]) // adapt this to your own reloading
    }

    private(set) lazy var users = reloadAction.elements
}
```

**Comment by lts1610** [comment]
Oh. it works nicely 💯 
But, I don't know why the `subject` is being constructed in `showUserAction`
``` swift 
   private lazy var showUserAction = Action<String, Void> { [unowned self] username in
        let subject = PublishRelay<Void>()
        subject
            .subscribe(onNext: { /* ... */ })
            .disposed(by: self.disposeBag)
        return self.router.rx.trigger(.user(username, dismissal: subject))
    }
```
Can you give me an explaination for this?

**Comment by pauljohanneskraft** [comment]
You can decide that on your own - whatever suits your current situation :) it might for example also make sense to change the type in the route to be `AnyObserver<Void>` - then you could also trigger the route with the inputs of the reloadAction directly

**Comment by lts1610** [comment]
Great! I got it. And I'm using `PublishRelay` in my project
Thank you again! 😃
