### ISSUE TITLE
Registered Interactive Transition for dismiss

### ISSUE THREAD

**Issue by adamsmaka** [quickbirdstudios/XCoordinator#56]
Hey, I'm trying to figure out how can I trigger interactive transition for dismiss route.
I found a good example how to implement it in your Examples folder.
```
    private func addPushGestureRecognizer(to container: Container) {
        let view = container.view
        let gestureRecognizer = UIScreenEdgePanGestureRecognizer()
        gestureRecognizer.edges = .right
        view?.addGestureRecognizer(gestureRecognizer)
        
        registerInteractiveTransition(
            for: .randomColor,
            triggeredBy: gestureRecognizer,
            progress: { [weak view] recognizer in
                let xTranslation = -recognizer.translation(in: view).x
                return max(min(xTranslation / UIScreen.main.bounds.width, 1), 0)
            },
            shouldFinish: { [weak view] recognizer in
                let xTranslation = -recognizer.translation(in: view).x
                let xVelocity = -recognizer.velocity(in: view).x
                return xTranslation >= UIScreen.main.bounds.width / 2
                    || xVelocity >= UIScreen.main.bounds.width / 2
            },
            completion: nil
        )
    }
```
But when we change route from `.randomColor` to `.users` which is a dismiss transition, animation happen immediately. I guess method name add**Push**GestureRecognizer is not called that by accident 😉
How can we achieve interaction transition for dismiss?

**Comment by pauljohanneskraft** [comment]
The dismiss transition does not directly specify an Animation object, which is why it cannot figure out, which animation to use. Setting the `animation` parameter in the transition creation should solve the issue.

**Comment by pauljohanneskraft** [comment]
We cannot otherwise get information about the animation of a transition, which is why it needs to be directly mentioned - it will however be mentioned in the code documentation that is coming in the next release ;-)

**Comment by adamsmaka** [comment]
Looks like it works! Thank you so much for so fast response :) It took me 3 days figuring it out 😂
