### ISSUE TITLE
Memory leak when pushing new coordinator to navigation coordinator

### ISSUE THREAD

**Issue by oliver-foggin** [quickbirdstudios/XCoordinator#57]
**How to replicate**

In your example app I have made this change in `AppCoordinator.swift` to make it easier to replicate...

```
        case .home:
            guard let presentable: Presentable = [
//                    HomeTabCoordinator(),
                    HomeSplitCoordinator(),
//                    HomePageCoordinator()
                ].randomElement() else {
                    return .none()
            }
            self.home = presentable
            return .present(presentable, animation: .staticFade)
```

Run this on an iPhone simulator in portrait mode (I have not tested in landscape but I imagine it will be the same.

Now press `Login`, `<Home`, `Logout` (repeat several times).

Open the `memory graph debugger`

You will see that there are now multiple instances of `NewCoordinator` (and others).

![screenshot 2019-01-09 at 11 59 54](https://user-images.githubusercontent.com/26765636/50898291-a6a98e80-1406-11e9-88ff-3afe9e438cc7.png)

**Cause of leak**

The transition to the news detail is pushing a Coordinator (`C`) which then dispenses a UIViewController (`V`). This is then on a navigation stack. So has a back button.

When the back button is tapped the view controller `V` is then popped from the navigation stack. But the coordinator `C` is still held in memory. Something along those lines anyway. I haven't had enough time to fully track it down at the moment but this should be enough to go by for now.

**Comment by pauljohanneskraft** [comment]
Thanks for finding this - it should be fixed in https://github.com/quickbirdstudios/XCoordinator/pull/58.
