### ISSUE TITLE
Multiple .embed(ed) view controllers

### ISSUE THREAD

**Issue by oronbz** [quickbirdstudios/XCoordinator#62]
Hi,
Solid coordinator framework!

I've noticed I can use `.embed` as a navigation transition to implement child view controllers.
But what if I need to embed multiple child view controllers at once? Should I trigger multiple routes at once?

And also, what would be the proper way of dismissing or switching those embedded view controllers?

Thanks!

**Comment by pauljohanneskraft** [comment]
Hey - thanks! You can always use `Transition.multiple` to chain different transitions together, so embedding multiple viewControllers could be done as in the following:

```swift
enum EmbedRoute: Route {
    /* ... */
    case embed([(presentable: Presentable, container: Container)])
}

class EmbedCoordinator: NavigationCoordinator<EmbedRoute> {
    /* ... */
    override func prepareTransition(for route: EmbedRoute) -> NavigationTransition {
        switch route {
        /* ... */
        case let .embed(embeds):
            return .multiple(embeds.map { .embed($0.presentable, in: $0.container) })
        }
    }
}

```

We currently do not support the switching of embedded view controllers, although you can add your own transitions using `Transition.init(presentable:animation:perform:)`. We propose defining static funcs on Transition which call this initializer. You can also look at the appropriate code documentation on the branch `feat/documentation`.

**Comment by oronbz** [comment]
So simple! Thanks!
