### ISSUE TITLE
What is notificationReceived?

### ISSUE THREAD

**Issue by Ricardo1980** [quickbirdstudios/XCoordinator#65]
Hello,

What is notificationReceived? Nobody is using it.
https://github.com/quickbirdstudios/XCoordinator/blob/master/Example/XCoordinator/Coordinators/AppCoordinator.swift#L59

Thanks.

**Comment by pauljohanneskraft** [comment]
It is an example of how you would use the deepLink transition - you would call it when there is some notification maybe. It is just there for illustrative reasons and is not called anywhere.
