### ISSUE TITLE
What happened to TransitionObservables in RxCoordinator?

### ISSUE THREAD

**Issue by Ricardo1980** [quickbirdstudios/XCoordinator#66]
Hello,

What happened to TransitionObservables in RxCoordinator?
Is there any migration guide (or ticket with a few sentences) about how to move from RxCoordinator to XCoordinator?

Thanks.

**Comment by pauljohanneskraft** [comment]
You can use `router.rx.trigger` for the presentation-observable. We removed the dismissal-observable, but there is an extension in the example-app which can be used as a substitute for it.

In general, the most important changes are, that AnyCoordinator should now be renamed to AnyRouter and transition(to:) was renamed to trigger(_:). The observables were removed as we removed our dependency on RxSwift (and moved RxSwift-specific code into the RxSwift-extension.)

**Comment by pauljohanneskraft** [comment]
Closed due to inactivity - Open again, if the question persists and the problem has not been resolved.
