### ISSUE TITLE
Optional linkage of RxSwift for Carthage

### ISSUE THREAD

**Issue by pauljohanneskraft** [quickbirdstudios/XCoordinator#76]
As stated in https://github.com/quickbirdstudios/XCoordinator/pull/74, optional linkage of RxSwift for XCoordinator would be beneficial for Carthage users as well. Since the PR did not solve the issue right away and further attention is required, this issue can be seen as a discussion/idea board and as a reminder.

**Comment by scogeo** [comment]
Danke for continuing to look into this.  I'm tossing in a couple links to other frameworks I use that are setup to build for multiple package management systems (CocoaPods, Carthage, Swift Package Manager, etc).  Unfortunately, as discussed in the original issue, the default CocoaPods project structure doesn't really work well for building for non-CocoaPods package managers.

Here's a couple projects that I use frequently:

- CoreStore (https://github.com/JohnEstropia/CoreStore)
- SwiftyBeaver (https://github.com/SwiftyBeaver/SwiftyBeaver)

Both of these contain multiple targets that are designed to build the same framework but target different platforms (iOS, watchOS, etc.)  The same concept could be used to build the framework with or without RxSwift.

Hope that helps.

**Comment by Ricardo1980** [comment]
Meanwhile, if you are interested, I forked this project and I removed everything about RxSwift.
https://github.com/Ricardo1980/XCoordinator
github "https://github.com/Ricardo1980/XCoordinator" "master"

**Comment by pauljohanneskraft** [comment]
With XCoordinator 2.0 (#122), it should be possible to use XCoordinator with Carthage without RxSwift by using the `XCoordinator.framework` file instead of `XCoordinatorRx.framework` (which includes RxSwift extensions) or `XCoordinatorCombine.framework` (which includes Combine extensions).
