### ISSUE TITLE
In the Example app, if i want UserListCoordinator push to UserViewController, how can i write the code?

### ISSUE THREAD

**Issue by protosse** [quickbirdstudios/XCoordinator#78]
the `UserViewModelImpl` already have a router `AnyRouter<UserRoute>`.
Should i consider to write two init methods?

**Comment by pauljohanneskraft** [comment]
So, you want the UserViewController to be pushed on the rootViewController of the UserListCoordinator? The easiest solution would probably be to just merge the `UserListRoute` and `UserRoute`.

If you think this would result in too much clutter and want them separated, you might want to have a look at RedirectionCoordinator/RedirectionRouter.

Another option (especially useful, if you want to use UserViewModelImpl in multiple routes) would be to create a protocol around all cases of the route the UserViewController uses. This protocol would look like this:

```
protocol FancyRouteProtocol {
    static func alert(title: String, message: String) -> Self
    static func users() -> Self
}
```

With this protocol, you are able to change the type of the viewModel to `UserViewModelImpl<FancyRoute: FancyRouteProtocol>` and the the router to `AnyRouter<FancyRoute>`.

**Comment by protosse** [comment]
maybe my question is if two Coordinator A and B, they have different routes, and they both want to push to the same controller, how can i declare the type of the router property in this Controller's ViewModelImpl.
i tried with this protocol but it's hard to write the code, so i use the first solution.
my app have a complex navigation, i find merge all routes to one maybe better😂.
thanks to answer.

**Comment by pauljohanneskraft** [comment]
That would be the perfect example of where a RedirectionCoordinator could be used - it has access to the superCoordinator's rootViewController but by using a different route type, you can still have independent flows.
