### ISSUE TITLE
What is registerPeek?

### ISSUE THREAD

**Issue by Ricardo1980** [quickbirdstudios/XCoordinator#81]
Hello, 
In the main screen:
https://github.com/quickbirdstudios/XCoordinator
I see:
```
case .registerUsersPeek(let source):
            return registerPeek(for: source, route: .users)
```
and
`    case registerUsersPeek(from: Container)`

What is that exactly? Is that a nested coordinator?

Thanks a lot.

**Comment by pauljohanneskraft** [comment]
As stated in the Documentation [here](https://quickbirdstudios.github.io/XCoordinator/Protocols/Coordinator.html#/s:12XCoordinator11CoordinatorPAARlzCrlE12registerPeek3for5routeAA10TransitionVyqd__GAA9Container_p_9RouteTypeQztSo16UIViewControllerCRbd__AI0gJ0RtzlF), you can register 3D Peek and Pop by performing transitions - After performing this transition, you can 3D Touch on the specified Container (i.e. UIView) to first show a preview of the to-be-transitioned-to ViewController (Peek). When the user 3D touches even harder the transition will be performed (Pop). Take a look at the [UIKit documentation](https://developer.apple.com/documentation/uikit/peek_and_pop) for more information of how this works.

**Comment by Ricardo1980** [comment]
Thanks!
