### ISSUE TITLE
Communicate a coordinator with another one

### ISSUE THREAD

**Issue by Ricardo1980** [quickbirdstudios/XCoordinator#82]
Hello,

Let's say I have an AppCoordinator, that contains coordinator First and coordinator Second.

AppCoordinator shows a view controller in First coordinator.
User presses a button (like Login)
Then AppCoordinator receives a signal and dismisses that view controller (that was presented modally) and releases First coordinator, after that, instantiates Second coordinator presenting another view controller (again, modally).

Basically, I want that when pressing that button, something happens not in that vc/vm coordinator, but in the parent coordinator.

I am not sure if this is exactly triggering a route.

Should I use a notification and put that logic there, inside the AppCoordinator, in a method called by a notification? Something like:
https://github.com/quickbirdstudios/XCoordinator/blob/master/Example/XCoordinator/Coordinators/AppCoordinator.swift#L59

BTW, in your sample code I see that after you login, that view controller stays alive, it is not released. That is exactly what I don't want.

Any suggestion about how to achieve this?

Thanks a lot.

**Comment by pauljohanneskraft** [comment]
Hey,

as far as I understand this question, it is only intended to ask how to connect parent and child coordinator, right? 

This depends on your own preference and the problem at hand. You have the following options (and possibly many more):
- post notifications in the child and observe them in the parent
- use reactive programming by injecting an observer (e.g. a subject) into the child coordinator, which the parent coordinator is subscribing to
- inject a closure - instantiate your child coordinator with a closure that is called whenever you want to trigger a specific action in the parent, the parent creates that closure and performs the intended action in it
- inject an AnyRouter from the parent coordinator and trigger routes, this however creates a dependency from the child coordinator to the parents route type

As I said, there are possibly many more solutions implementing the publish-subscriber pattern. In my personal opinion, I would choose either reactive programming or injecting closures as it creates the least dependencies between the types of child and parent coordinator.

**Comment by pauljohanneskraft** [comment]
I assume this issue has been resolved, as it has been inactive for a while now - Feel free to add further comments, if there are any unresolved questions.

**Comment by NIKMC** [comment]
Hello, I have a question about communication between coordinator through AppCoordinator and how to use deepLink inside AppCoordinator.
So, I'll try to tell you more detail what I need. In your Readme, you described how and when to call AppCoordinator inside AppDelegate.

``` swift
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    let window: UIWindow! = UIWindow()
    let router = AppCoordinator().anyRouter

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        router.setRoot(for: window)
        return true
    }
}

```
If I right understood, we initialise AppCoordinator before  `func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool` has been called. 

But what should I do, if `func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([Any]?) -> Void) -> Bool` where the function is called first and I need to open various screens which depends from incoming data. But it couldn't  be happen, because AppCoordinator has been initialised earlier  and deepLink will not work, if I call router.trigger. For example:
``` swift
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    let window: UIWindow! = UIWindow()
    let router = AppCoordinator().anyRouter

    func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([Any]?) -> Void) -> Bool {
        router.setRoot(for: window)
let codeString = userActivity.webpageURL! //Doesn't matter 
        router.trigger(.callDeepLink(codeString))
       return true
}

```

```
//AppCoordinator
enum AppRoute: Route {
    case auth
    case main(Int)
    case callDeepLink(String)
}
class AppXCoordinator: NavigationCoordinator<AppRoute> {
    private var home: Presentable?
    init() {
           super.init(initialRoute: .auth) 
    }
    
    override func prepareTransition(for route: AppRoute) -> NavigationTransition {
        switch route {
        case .auth:
            let coordinator = AuthCoordinator()
            self.home = coordinator
            .......
            return .presentOnRoot(coordinator, animation: animation)
        case let .main(page):
            let coordinator: Presentable = HomeTabCoordinator(pageIndex: page)
            self.home = coordinator
             ....
            return .presentOnRoot(coordinator, animation: animation)
        case let . callDeepLink(code):
            return deepLink(AppRoute.auth, AuthRoute.recreatePassword(code))
        }
    }
}


```

DeepLink does not work if the application has been completely unloaded from memory.
