### ISSUE TITLE
-UIViewShowAlignmentRects YES will crash

### ISSUE THREAD

**Issue by Superoryco** [quickbirdstudios/XCoordinator#93]
I am using this excellent coordinator pattern in my project, every thing goes fine until I run project with "-UIViewShowAlignmentRects YES"

To reproduce the problem, just use the XCoordinator Example project and set Run Scheme->Arguments-> Arguments Passed On Launch->-UIViewShowAlignmentRects YES

According to the log:	
23  XCoordinator                        0x0000000102ebe883 $s12XCoordinator11PresentablePAAE7setRoot3forySo8UIWindowC_tF + 227

May be it has something to do with the way on how XCoordinator been set up in "didFinishLaunchingWithOptions"?

**Comment by Superoryco** [comment]
Logs:

*** Assertion failure in -[UIVisualEffectView _addSubview:positioned:relativeTo:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3698.103.12/UIVisualEffectView.m:1859
2019-05-22 21:50:09.533798+0800 XCoordinator_Example[91060:7541153] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '<_UIDebugAlignmentRectView: 0x7f9e25f0a7f0; frame = (0 0; 375 44); opaque = NO; autoresize = W+H; userInteractionEnabled = NO; layer = <CALayer: 0x600002cb8460>> has been added as a subview to <UIVisualEffectView: 0x7f9e25c083d0; frame = (0 0; 375 44); layer = <CALayer: 0x600002cd3460>>. Do not add subviews directly to the visual effect view itself, instead add them to the -contentView.'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000104d026fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000102fd5ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000104d02482 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x0000000101f9f927 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   UIKitCore                           0x000000010d69e370 -[UIVisualEffectView _addSubview:positioned:relativeTo:] + 364
	5   UIKitCore                           0x000000010e33b98c -[UIView(UIConstraintBasedLayout) _alignmentDebuggingOverlayCreateIfNecessary:] + 591
	6   UIKitCore                           0x000000010e40bc34 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2044
	7   QuartzCore                          0x000000010707ceae -[CALayer layoutSublayers] + 173
	8   QuartzCore                          0x0000000107081b88 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 396
	9   UIKitCore                           0x000000010e3f6985 -[UIView(Hierarchy) layoutBelowIfNeeded] + 646
	10  UIKitCore                           0x000000010d88d585 -[UINavigationController _positionNavigationBarHidden:edge:initialOffset:] + 800
	11  UIKitCore                           0x000000010d88d804 -[UINavigationController _positionNavigationBarHidden:edge:] + 388
	12  UIKitCore                           0x000000010d897de7 -[UINavigationController _updateBarsForCurrentInterfaceOrientationAndForceBarLayout:] + 145
	13  UIKitCore                           0x000000010d943a8d -[UIViewController viewDidMoveToWindow:shouldAppearOrDisappear:] + 1184
	14  UIKitCore                           0x000000010d894d0e -[UINavigationController viewDidMoveToWindow:shouldAppearOrDisappear:] + 49
	15  UIKitCore                           0x000000010e402962 -[UIView(Internal) _didMoveFromWindow:toWindow:] + 1414
	16  UIKitCore                           0x000000010e3f54ee __45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke + 151
	17  UIKitCore                           0x000000010e3f53cd -[UIView(Hierarchy) _postMovedFromSuperview:] + 795
	18  UIKitCore                           0x000000010e40563d -[UIView(Internal) _addSubview:positioned:relativeTo:] + 1948
	19  UIKitCore                           0x000000010df73fbc -[UIWindow addRootViewControllerViewIfPossible] + 1027
	20  UIKitCore                           0x000000010df74327 -[UIWindow _setHidden:forced:] + 289
	21  UIKit                               0x0000000120ac9bbd -[UIWindowAccessibility _orderFrontWithoutMakingKey] + 86
	22  UIKitCore                           0x000000010df86f86 -[UIWindow makeKeyAndVisible] + 42
	23  XCoordinator                        0x0000000102ebe883 $s12XCoordinator11PresentablePAAE7setRoot3forySo8UIWindowC_tF + 227
	24  XCoordinator_Example                0x0000000101b3eac7 $s20XCoordinator_Example11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0k6LaunchJ3KeyaypGSgtF + 359
	25  XCoordinator_Example                0x0000000101b3ec34 $s20XCoordinator_Example11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0k6LaunchJ3KeyaypGSgtFTo + 196
	26  UIKitCore                           0x000000010df35311 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 280
	27  UIKitCore                           0x000000010df36cad -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 3932
	28  UIKitCore                           0x000000010df3c0c6 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1617
	29  UIKitCore                           0x000000010d7816d6 __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke + 904
	30  UIKitCore                           0x000000010d789fce +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 153
	31  UIKitCore                           0x000000010d7812ec -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 236
	32  UIKitCore                           0x000000010d781c48 -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 1091
	33  UIKitCore                           0x000000010d77ffba __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 782
	34  UIKitCore                           0x000000010d77fc71 -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 433
	35  UIKitCore                           0x000000010d7849b6 __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 576
	36  UIKitCore                           0x000000010d785610 _performActionsWithDelayForTransitionContext + 100
	37  UIKitCore                           0x000000010d78471d -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 223
	38  UIKitCore                           0x000000010d7896d0 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 392
	39  UIKitCore                           0x000000010df3a9a8 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 514
	40  UIKitCore                           0x000000010daf1dfa -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 361
	41  FrontBoardServices                  0x000000010ca70125 -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 448
	42  FrontBoardServices                  0x000000010ca79ed6 __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 283
	43  FrontBoardServices                  0x000000010ca79700 __40-[FBSWorkspace _performDelegateCallOut:]_block_invoke + 53
	44  libdispatch.dylib                   0x0000000106568db5 _dispatch_client_callout + 8
	45  libdispatch.dylib                   0x000000010656c2ba _dispatch_block_invoke_direct + 300
	46  FrontBoardServices                  0x000000010caab146 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
	47  FrontBoardServices                  0x000000010caaadfe -[FBSSerialQueue _performNext] + 451
	48  FrontBoardServices                  0x000000010caab393 -[FBSSerialQueue _performNextFromRunLoopSource] + 42
	49  CoreFoundation                      0x0000000104c69be1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	50  CoreFoundation                      0x0000000104c69463 __CFRunLoopDoSources0 + 243
	51  CoreFoundation                      0x0000000104c63b1f __CFRunLoopRun + 1231
	52  CoreFoundation                      0x0000000104c63302 CFRunLoopRunSpecific + 626
	53  GraphicsServices                    0x000000010a2872fe GSEventRunModal + 65
	54  UIKitCore                           0x000000010df3dba2 UIApplicationMain + 140
	55  XCoordinator_Example                0x0000000101b3f03b main + 75
	56  libdyld.dylib                       0x00000001065dd541 start + 1
	57  ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by Superoryco** [comment]
Turns out to be that XCoordinator will also fail all the functions in Xcode>Debug>View Debugging menu
Any solution?

**Comment by pauljohanneskraft** [comment]
I managed to reproduce this without XCoordinator involved at all, so this seems to be a UIKit bug.

This was the code I used:
```swift
import UIKit

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    let window: UIWindow! = UIWindow()

    func application(_ application: UIApplication,
                     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        window?.rootViewController = UINavigationController(rootViewController: UIViewController())
        window?.makeKeyAndVisible()
        return true
    }
}
```

If you can further pin this problem down and/or gather information that links this to XCoordinator instead of UIKit, feel free to add further comments/reopen this issue.
