### ISSUE TITLE
Does Xcoordinator support Custom Container ViewController?

### ISSUE THREAD

**Issue by Superoryco** [quickbirdstudios/XCoordinator#94]
If it does, how can I implement?

**Comment by Superoryco** [comment]
Sorry...
Founded:

Full support for your own coordinator classes conforming to our Coordinator protocol
You can also start with one of the following types to get a head start: NavigationCoordinator, ViewCoordinator, TabBarCoordinator and more.

**Comment by pauljohanneskraft** [comment]
Hey - great to hear that you found an answer to your question! 

It might be a bit too much work to write your coordinator completely from scratch and implement the Coordinator protocol, you can use the BaseCoordinator as a super class as well to get the common functionality of all other provided coordinator classes. To get more help on how to implement your custom coordinator classes for your own rootViewController classes, a look at the implementations of NavigationCoordinator, TabBarCoordinator, SplitCoordinator, etc might help here. If you have any remaining questions, feel free to reopen or open additional issues.
