### ISSUE TITLE
What is the best practice to present a modal UIViewController?

### ISSUE THREAD

**Issue by gtatgh** [quickbirdstudios/XCoordinator#95]
I want to present a modal UIViewController. What is the best practice to show and dismiss it?

**Comment by pauljohanneskraft** [comment]
Use the `.present` transition to show the viewController and the `.dismiss` transition to dismiss it. 

I'm not sure, whether that fully answers your questions... Please be more specific and make sure to read the README, if you have further questions.

**Comment by gtatgh** [comment]
@pauljohanneskraft Thanks for explanation!
