### ISSUE TITLE
Embed an UIViewController in an UIView

### ISSUE THREAD

**Issue by gtatgh** [quickbirdstudios/XCoordinator#96]
Hello,

I need some help to embed an `UIViewController` in an `UIView`. I have following screen separation:
### A controller to present
```
----------------------
|  Placeholder View  | <- Here I want to embed a top bar
----------------------
|                    |
|         Main       |
|                    |
----------------------
```
### A controller to embed
```
----------------------
|       Top Bar      |
----------------------
```
 If I do something like
```
let viewController = MainViewController(...)
let topBar = TopBarViewController(...)
return .multiple(.push(viewController), .embed(topBar, in: viewController))
```
Then a whole view of `UIViewController` displays a top bar.

I can't specify to embed in a placeholder view, because this view is not initialized at the moment.
```
let viewController = MainViewController(...)
let topBar = TopBarViewController(...)
// viewController.placeholderView is nil at the moment
return .multiple(.push(viewController), .embed(topBar, in: viewController.placeholderView))
```
What can I do to embed `TopBarViewController` in a placeholder view?

**Comment by pauljohanneskraft** [comment]
You can call `viewController.viewLoadIfNeeded()` before your return statement, then the view should be initialized before performing any transitions. Additionally, your `placeholderView` should not be nil after that call.

**Comment by gtatgh** [comment]
It sounds interesting. I need to call `viewController.loadViewIfNeeded()` for each `UIViewController` is it right?

**Comment by pauljohanneskraft** [comment]
If you need any IBOutlet and you cannot be sure that it is not nil (since it may not be loaded yet), you can simply call `viewController.loadViewIfNeeded()`. So, you do not need to call it for every viewController in general, just for when you want to access an IBOutlet and cannot be sure it has already been loaded.

**Comment by gtatgh** [comment]
@pauljohanneskraft Thank you!
